### PR TITLE
merge Staging

### PR DESCRIPTION
**Pull request by milestorme**
fix build warning , update module to match skeleton and fix travis build errors and update readme

### CODE REVIEW

**Comment by icecatbing** [comment]
Nice work!
I'll running the PR after work.

**Comment by BarbzYHOOL** [comment]
@icecatbing don't forget to tell us the result!

**Comment by milestorme** [comment]
compiled myself on AC>AzerothCore rev. dfdedd36bb20+ 2019-05-30 12:30:23 +0200 (master branch) (Unix, Release) waiting for the weekend to see if its working as it should, the script has Friday Saturday and sunday as the weekend and a custom announcement that its started

**Comment by talamortis** [comment]
Nice work, Thanks!

its also nice to see people are still committing to my work of modules and still trying to improve them for the latest versions of AC!

**Pull request merged**
